---
title: "Cytokine analysis - Serum"
author: "Kaare"
date: "11th October 2022"    
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE)
```

```{r load packages, include=FALSE}
library(readxl) 
library(tidyverse)
library(gt)
library(gtsummary)
library(broom)
library(rstatix)
library(knitr)
library(patchwork)
library(ggpubr)
```
#README: 
Serum cytokines only

# Data import
```{r adjust_data, echo=TRUE}
#_______Import dataset and Transform to adjusted values_______#

cytokines <- read_excel("data/processed/cytokines.xlsx") %>% 
  filter(tissue != "ileum") %>% 
  pivot_longer(.,
               cols = INFg:TNFa ,
               names_to = "variables",
               values_to = "values"
  ) %>% 
  drop_na(values) %>% 
   pivot_wider(
    id_cols = c(
      sample_id,exp_number, group, received_antibiotics,maternal_treatment, type_of_feed, tissue,),
    names_from = variables, 
    values_from = values)


#____ Make long format _______#
cytokines_long <- cytokines %>%
  pivot_longer(.,
               cols = INFg:TNFa ,
               names_to = "variables",
               values_to = "values"
  )
```

# Exp1

## Check for data distribution. 
```{r Exp1 visualize data, eval=FALSE, include=FALSE}
cytokines_long %>%                       #normality_check  of cytokine distributions
  filter(exp_number == 1) %>% 
  #filter(variables != "INFg") %>% 
  drop_na(values) %>% 
  group_by(variables, group) %>% 
  shapiro_test(values)

#log10 transformed shapiro_test - failed variables
cytokines_long %>% 
 filter(exp_number == 1) %>% 
  filter(variables != "INFg") %>% 
  drop_na(values) %>% 
  mutate(values = log10(values)) %>% 
  group_by(variables, group) %>% 
  shapiro_test(values) %>% 
  filter(p < 0.05)

#  group    variables variable statistic       p
#  <fct>    <chr>     <chr>        <dbl>   <dbl>
# VANCO-BF IL-1b     values       0.727 0.00728     # transformation helped.

#Density plots to show distribution of cytokines
histogram <- cytokines_long %>% 
   filter(exp_number == study_round) %>% 
  filter(tissue == sample_tissue) %>%
  #filter(variables != "INFg") %>% 
  drop_na(values) %>% 
  ggplot(aes(x = values, fill = group)) + 
  geom_histogram() +
  facet_wrap(~ variables, ncol = 2,
             scales = "free")

log10_histogram <- cytokines_long %>% 
   filter(exp_number == study_round) %>% 
  filter(tissue == sample_tissue) %>%
  #filter(variables != "INFg") %>% 
  drop_na(values) %>% 
  ggplot(aes(x = log10(values), fill = group)) + 
  geom_density() +
  facet_wrap(~ variables, ncol = 2,
             scales = "free")

#Jitter plots. Works
jitter_plot <- cytokines_long %>% 
   filter(exp_number == study_round) %>% 
  filter(tissue == sample_tissue) %>%
  #filter(variables != "INFg") %>% 
  drop_na(values) %>% 
  ggplot(aes(x = group, y = values, color = group)) +
  geom_jitter() +
  facet_wrap(~ variables,
             scales = "free") 

log10_jitter_plot <- cytokines_long %>% 
   filter(exp_number == study_round) %>% 
  filter(tissue == sample_tissue) %>%
  filter(variables != "INFg") %>% 
  drop_na(values) %>% 
  mutate(adjusted_values = log10(values)) %>% 
  ggplot(aes(x = group, y = values, color = group)) +
  geom_jitter() +
  facet_wrap(~ variables,
             scales = "free") 
```

##Table

```{r Exp1-table}
#_____Currently non-normally distributed values are plotted as median (IQR)____# 
 #change statistics with help from here: https://www.danieldsjoberg.com/gtsummary/reference/tests.html 

Exp1_tbl1 <- cytokines %>% 
  filter(exp_number == "1") %>%
  select(group, INFg:TNFa) %>% 
  tbl_summary(by = group,
              digits = everything() ~ c(2,2,2),
              missing = "no",
              #include = !"INFg",
              #type = all_continuous() ~ "continuous2",
              statistic = all_continuous() ~ #c("{mean} ({sd})",         
                                     "{median} ({p25}, {p75})") %>%
  modify_header(
    label ~ "**Groups:**") %>% 
   #modify_footnote(stat_1 ~ "Median (IQR)", stat_2 ~ "p-value on overall group differences,Kruskall-Wallis rank sum test ") %>% 
add_p() %>% 
  as_gt() %>%
  tab_header(title = md("**Serum concentraions of proinflammatory cytokines** *(pg/ml)*")) %>%
  opt_align_table_header("center") %>% 
   tab_options(heading.title.font.size = 15,
               heading.background.color = "lightgrey",
               ) %>% 
     tab_source_note(
    source_note = "Matrinem Experiment 1"
  ) 


Exp1_tbl1 %>%
  gtsave(path = "exports/cytokines/", filename = "Exp1-serum-adjusted.png")
```

## Plot
To see all the cytokine leves plotted run this code: 
```{r plots all cytokines, warning=FALSE}

Exp1_plot_all_cytokines <- cytokines_long %>%
  filter(exp_number == "1") %>% 
  #filter(!variables %in% c("INFg", "IL-12p70")) %>%
ggplot(aes(x = group, 
           y = values, 
           fill = group)) + 
  geom_boxplot(outlier.shape = NA) +
  stat_compare_means(aes(label = ..p.signif..),
                   method = "wilcox.test", ref.group = "CON-BF",
                   label.y.npc = 0.55) +
  facet_wrap(~variables, 
             scales = 'free', 
             nrow = 2,
             ncol = 5) +
  labs(title = "Concentraion of pro-inflammatory cytokines in serum",
       x = "",
       y = "Tissue conc. (pg/ml)",
       fill = "Groups") +
  theme_bw()+
  theme(                   # Change the appearance of labels
    plot.title = element_text(color="darkgrey", size=12, face="bold"),
    axis.title.y = element_text(color="darkgrey", size=10, face="bold.italic"),
    #axis.text.y = element_blank(),
    axis.ticks.x = element_blank(),  # Hide labels
    axis.text.x = element_blank(),
    legend.title = element_text(face="bold"),   
    legend.position="bottom",
    legend.background = element_rect(fill="white")) + # Change legend box background color
  scale_fill_brewer(palette="Set1") + plot_annotation (
  #title = 'Cytokine expression',
   #subtitle = 'All cytokines measured',
  #tag_levels = 'A',
  caption = 'CON = Water, AB = Antibiotics, BF = Breast-Feeding, FF = Formula-Feeding',
  theme = theme(plot.title = element_text(hjust = 0.5, size=14, face="bold"),
                plot.subtitle = element_text(hjust = 0.5, face = "bold.italic"),
                plot.caption = element_text(hjust = 0.5, size=7,face = "bold")))
  
Exp1_plot_all_cytokines
ggsave(width = 170, height = 120, units = "mm",'exports/cytokines/Exp1-serum-adjusted-plot.png',Exp1_plot_all_cytokines)
```
