---
title: "HISTO1"
author: "Kaare"
date: "6/27/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## MATRINEM histo-analysis. 
AB-PAS stains quantified as % of total tissue. Experiments 2-4 collected samples for histology, but not experiment 1. 
Samples are of ileum (small intestine) and colon collected from mouse pups 6 days postnatally.

```{r load packages, include=FALSE}
# Packages required
library(readxl)
library(dplyr)
library(tidyverse)
```


```{r}
data <- read_excel("../../Data/RawData/Histo_analysis .xlsx")
chars <- read_excel("../../Data/CleanData/study_id_info.xlsx")

```

```{r}
histo <- data %>% 
  mutate(ID = str_remove(ID, "-C") %>% str_remove(.,"-I") %>% str_remove(.," I")) %>% 
  mutate(ID = as.numeric(ID)) %>% 
  rename(sample_id = ID)


histo <- histo %>%  
  left_join(., chars, by = "sample_id") %>% 
  select(sample_id:`AB-RELATIVE-TO-TOTAL(%)`,group2, exp_number) %>% 
  relocate(., exp_number, group2, .after = sample_id) 

```

Ileum plots are shown below for round 4

```{r}

```

```{r}
tissue <- "ileum"
round <- "4"

####Bar char 
histo %>%  
  filter(TISSUE == tissue & exp_number == round) %>% 
  group_by(group2) %>% 
  summarise(mean = mean(`AB-RELATIVE-TO-TOTAL(%)`)) %>% 
  ggplot(
    aes(x = group2 
        ,y = mean 
        ,fill = group2
        )) +
  geom_bar(stat = "identity") + 
  labs(title =  paste(tissue ,"AB staining % of total tissue"), subtitle = "No subtitle",
       y = "% of tissue AB stained (mucin thickness?)",
       x = "Treatment groups") + 
  theme_bw()


####Boxplot char 
histo %>%  
  filter(TISSUE == tissue & exp_number == round) %>% 
  ggplot(
    aes(x = group2 
        ,y = `AB-RELATIVE-TO-TOTAL(%)` 
        ,fill = group2
        )) +
  geom_boxplot() + 
  labs(title =  paste(tissue ,"AB staining % of total tissue"), subtitle = "No subtitle",
       y = "% of tissue AB stained (mucin thickness?)",
       x = "Treatment groups") + 
  theme_bw()

```

```{r}
tissue <- "colon"
round <- "4"

####Bar char 
histo %>%  
  filter(TISSUE == tissue & exp_number == round) %>% 
  group_by(group2) %>% 
  summarise(mean = mean(`AB-RELATIVE-TO-TOTAL(%)`)) %>% 
  ggplot(
    aes(x = group2 
        ,y = mean 
        ,fill = group2
        )) +
  geom_bar(stat = "identity") + 
  labs(title =  paste(tissue ,"AB staining % of total tissue"), subtitle = tissue,
       y = "% of tissue AB stained (mucin thickness?)",
       x = "Treatment groups") + 
  theme_bw()


####Boxplot char 
histo %>%  
  filter(TISSUE == tissue & exp_number == round) %>% 
  ggplot(
    aes(x = group2 
        ,y = `AB-RELATIVE-TO-TOTAL(%)` 
        ,fill = group2
        )) +
  geom_boxplot() + 
  labs(title =  paste(tissue ,"AB staining % of total tissue"), subtitle = "No subtitle",
       y = "% of tissue AB stained (mucin thickness?)",
       x = "Treatment groups") + 
  theme_bw()

```



