---
title: "HISTO1"
author: "Kaare"
date: "6/27/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## MATRINEM histo-analysis. 
AB-PAS stains quantified as % of total tissue. Experiments 2-4 collected samples for histology, but not experiment 1. 
Samples are of ileum (small intestine) and colon collected from mouse pups 6 days postnatally.

```{r load packages, include=FALSE}
# Packages required
library(readxl)
library(dplyr)
library(tidyverse)
```
```{r}
data <- read_excel("Data_files/Histo analysis .xlsx")
allrounds <- read_excel("Data_files/bodyweight_round_1234.xlsx")

```

```{r}
clean_data <- data %>% 
  mutate(ID = str_remove(ID, "-C") %>% str_remove(.,"-I") %>% str_remove(.," I")) %>% 
  mutate(ID = as.numeric(ID))

filter_joined_df <- semi_join(allrounds, clean_data, by = c("sample_id" = "ID")) 

histo <- filter_joined_df %>% 
  inner_join(clean_data, by = c("sample_id" = "ID"))

histo <- histo %>% 
  pivot_longer(., `PAS-RELATIVE-TO-TOTAL(%)`:`AB-RELATIVE-TO-TOTAL(%)`, 
               names_to = "AB-PAS",
               values_to = "% of total tissue stained")
  

```


```{r}
histo %>%  ### Try to wrap histo longer to have all stain values in 1 column and facet-wrap by PAS + AB
  filter(TISSUE == "ileum") %>% 
  ggplot(aes(x = received_antibiotic, y = `% of total tissue stained`)) +
  geom_boxplot() + 
  facet_wrap(~ experiment_no) +
  labs(title =  "Ileum AB-PAS staining % of total tissue", subtitle = "Faceted by experimental round (2-4)",
       x = "Maternal Treatment") + 
  theme_bw()

```


```{r}
histo %>% 
  filter(TISSUE == "colon") %>% 
   ggplot(aes(x = received_antibiotic, y = `% of total tissue stained`)) +
  geom_boxplot() + 
  facet_wrap(~ experiment_no) +
  labs(title =  "COLON AB-PAS staining % of total tissue", subtitle = "Faceted by experimental round (2-4)",
       x = "Maternal Treatment") + 
  theme_bw()

```
Visually no effect. 

